version: '3.8'

services:
  web:
    depends_on:
      - api
    build: 
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    env_file:
      - .env.frontend
    restart: unless-stopped

  api:
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    env_file:
      - .env.backend
    environment:
      DB_URL: mongodb://db/vaults
    restart: unless-stopped

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vaults:/data/db
    restart: unless-stopped

  # watchtower:
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 30

volumes:
  vaults: