version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - 80:3000

  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vaults

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vaults:/data/db

volumes:
  vaults: