version: '3.8'

services:
  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - 80:3000
    volumes:
      - ./frontend:/app
    env_file:
      - .env.dev.frontend
    environment:
      - WDS_SOCKET_PORT=80

  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    env_file:
      - .env.dev.backend
    environment:
      DB_URL: mongodb://db/vaults
    command: npm run dev

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vaults:/data/db

volumes:
  vaults: