version: '3.8'

services:
  web:
    depends_on:
      - api
    build: 
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80

  api:
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vaults

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vaults:/data/db

volumes:
  vaults: